library(ggplot2)
library(plotly)
library(dplyr)
library(forcats)
library(shinydashboard)
library(shiny)
library(shinycssloaders)
library(ggrepel)
library(shinyWidgets)

master_df <- read.csv("CBB_Data_2020.csv")
gamelogs_df <- read.csv("GameLog_Data_2020.csv")

master_df$Class <- factor(master_df$Class, levels = c("Freshman", "Sophmore", "Junior", "Senior"))
gamelogs_df$Class <- factor(gamelogs_df$Class, levels = c("Freshman", "Sophmore", "Junior", "Senior"))